spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    schema: classpath:sql/h2/schema.sql
    #data: classpath:sql/h2/data.sql

logging:
  level:
    root: DEBUG
    com:
      github:
        javarunfast:
          mbye: TRACE
