spring:
  profiles:
    active: dev
  devtools:
    remote:
      secret: test
      debug:
        local-port: 14001
    restart:
      enabled: true
  freemarker:
    checkTemplateLocation: false

  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
